# This file gives explicit instructions to Netlify on how to build your site.
# It overrides the automatic detection that was causing the error.

[build]
  # This tells Netlify to run your frontend build script.
  command = "npm run build"
  
  # This tells Netlify where to find the finished website files.
  # Vite's default output folder is "dist".
  publish = "dist"
